// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('ggyt', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('ggyt', async function() {
    await driver.get("https://www.google.com//")
    await driver.setRect(994, 700)
    await driver.findElement(By.name("q")).sendKeys("youtube")
    await driver.findElement(By.name("q")).sendKeys(Key.ENTER)
    await driver.findElement(By.css(".g > div > div > .rc .ellip")).click()
    await driver.findElement(By.css(".style-scope:nth-child(2) > #endpoint > #icon")).click()
    {
      const element = await driver.findElement(By.css(".style-scope:nth-child(2) > #endpoint > #icon"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.css(".style-scope:nth-child(2) > #endpoint"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".style-scope:nth-child(1) > #contents > .style-scope > #dismissable > #contents #grid-container > .style-scope:nth-child(1) #img")).click()
  })
})
